# Generated by Django 4.2.24 on 2025-09-30 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(blank=True, max_length=30, null=True)),
                ('Description', models.CharField(blank=True, max_length=300, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('PointsEligible', models.CharField(blank=True, max_length=30, null=True)),
                ('ProductImage', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=30, null=True)),
                ('Password', models.CharField(blank=True, max_length=30, null=True)),
                ('UserType', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
                ('Description', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
                ('Address', models.CharField(blank=True, max_length=300, null=True)),
                ('Email', models.CharField(blank=True, max_length=30, null=True)),
                ('Mobno', models.BigIntegerField(blank=True, null=True)),
                ('District', models.CharField(blank=True, max_length=30, null=True)),
                ('City', models.CharField(blank=True, max_length=30, null=True)),
                ('Pin', models.BigIntegerField(blank=True, null=True)),
                ('LOGINID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BottleBucksApp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='RewardTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Points', models.IntegerField(blank=True, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BottleBucksApp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='AccountTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACno', models.BigIntegerField(blank=True, null=True)),
                ('IFSCcode', models.CharField(blank=True, max_length=30, null=True)),
                ('Proof', models.FileField(blank=True, null=True, upload_to='')),
                ('UPI', models.CharField(blank=True, max_length=30, null=True)),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BottleBucksApp.usertable')),
            ],
        ),
    ]
