# Generated by Django 4.2.24 on 2025-10-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BottleBucksApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gifttable',
            old_name='ProductImage',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='gifttable',
            old_name='ProductName',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='gifttable',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='notificationtable',
            name='Description',
        ),
    ]
