# Generated by Django 4.2.24 on 2025-10-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BottleBucksApp', '0002_rename_productimage_gifttable_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gifttable',
            old_name='Image',
            new_name='ProductImage',
        ),
        migrations.RenameField(
            model_name='gifttable',
            old_name='Name',
            new_name='ProductName',
        ),
        migrations.AddField(
            model_name='gifttable',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
