# Generated by Django 4.2.24 on 2025-11-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BottleBucksApp', '0003_rename_image_gifttable_productimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucksHistoryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Bucks', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedeemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Method', models.CharField(blank=True, max_length=50, null=True)),
                ('Bucksused', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='usertable',
            old_name='Mobno',
            new_name='Phno',
        ),
        migrations.AddField(
            model_name='notificationtable',
            name='Description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='notificationtable',
            name='Image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
