# Generated by Django 4.2.24 on 2025-11-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BottleBucksApp', '0004_buckshistorytable_redeemhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttable',
            name='Bankname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
