# Generated by Django 4.2.24 on 2025-11-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BottleBucksApp', '0005_accounttable_bankname'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttable',
            name='Name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
