# Generated by Django 4.2.24 on 2025-12-02 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BottleBucksApp', '0006_accounttable_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalRewardSpend', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('PRODUCTID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BottleBucksApp.gifttable')),
                ('USERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BottleBucksApp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimPointAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BottleBucksApp.accounttable')),
                ('USERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BottleBucksApp.usertable')),
            ],
        ),
    ]
