# Generated by Django 4.2.24 on 2025-12-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BottleBucksApp', '0007_claimproduct_claimpointaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
