# Generated by Django 4.2.24 on 2025-12-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BottleBucksApp', '0008_usertable_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifttable',
            name='PointsEligible',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
