# Generated by Django 4.2.24 on 2025-12-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BottleBucksApp', '0009_alter_gifttable_pointseligible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifttable',
            name='Quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
