# Generated by Django 4.2.24 on 2025-12-02 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BottleBucksApp', '0010_alter_gifttable_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttable',
            name='Name',
        ),
    ]
