# Generated by Django 4.2.24 on 2025-12-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BottleBucksApp', '0011_remove_accounttable_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimpointaccount',
            name='redeemmoney',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
