# Generated by Django 4.2.24 on 2025-12-02 08:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BottleBucksApp', '0012_claimpointaccount_redeemmoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimpointaccount',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claimpointaccount',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
