# Generated by Django 4.2.24 on 2025-12-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BottleBucksApp', '0013_claimpointaccount_date_claimpointaccount_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttable',
            name='Name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
