# Generated by Django 4.2.24 on 2025-12-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BottleBucksApp', '0014_accounttable_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimproduct',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
