# Generated by Django 4.2.24 on 2025-12-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BottleBucksApp', '0015_claimproduct_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
