# Generated by Django 4.2.24 on 2025-12-15 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BottleBucksApp', '0016_usertable_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='City',
        ),
    ]
