# Generated by Django 4.2.24 on 2025-12-15 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BottleBucksApp', '0017_remove_usertable_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtable',
            name='Image',
        ),
        migrations.AddField(
            model_name='notificationtable',
            name='USER_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BottleBucksApp.usertable'),
        ),
    ]
