# Generated by Django 4.2.24 on 2025-12-16 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BottleBucksApp', '0018_remove_notificationtable_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttable',
            name='Proof',
        ),
    ]
